### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by maavia10** [IntuitivTechnology/InputMaskBundle#2]
please let em know how its work ?
i have configure according to config documents but it show nothing

**Comment by pierre-vassoilles** [comment]
Ok, I don't really see what you've done and what you haven't done in your project...
Please can you copy and paste your code for the files : 
- app/config.yml
- app/AppKernel.php
- The Symfony form class where you try to use the inputmask type

Thanks ;)

**Comment by pierre-vassoilles** [comment]
No answer, closing issue.
